### ISSUE TITLE
should rocks work with docker import?

### ISSUE THREAD

**Issue by PietroPasotti** [canonical/rockcraft#186]
Maybe I'm misunderstanding what `docker import` is for, but in order to locally verify a rock I was trying to:
`docker import ./traefik_2.9.6_amd64.rock trfk`. The command would succeed.

However, `docker run trfk` would fail with `docker: Error response from daemon: No command specified.`.
Inspecting the image with `dive` showed that the image was somehow corrupted, showing tar archives instead of the expected directory tree.

Using `skopeo copy` worked: `dive` shows the directory tree and `docker run` runs the image without errors.
The question is: should `docker import` also work, and why does it fail?

**Comment by cjdcordeiro** [comment]
Hi @PietroPasotti 

**Short answer:** no.

----

#### Explanation:

##### docker import

`docker import` is meant to import a raw filesystem from a tarball, without any metadata. Here's an exercise:

```bash
$ docker run -d --name my-container ubuntu sleep 30
$ docker export my-container -o my-container-fs.tar
$ tar -tvf my-container-fs.tar | tail -10
-rw-r--r-- 0/0          172284 2023-01-26 03:06 var/log/dpkg.log
-rw-r--r-- 0/0            3232 2023-01-26 03:03 var/log/faillog
-rw-rw-r-- 0/43          29492 2023-01-26 03:03 var/log/lastlog
-rw-rw-r-- 0/43              0 2023-01-26 03:03 var/log/wtmp
drwxrwsr-x 0/8               0 2023-01-26 03:03 var/mail/
drwxr-xr-x 0/0               0 2023-01-26 03:03 var/opt/
lrwxrwxrwx 0/0               0 2023-01-26 03:03 var/run -> /run
drwxr-xr-x 0/0               0 2023-01-26 03:03 var/spool/
lrwxrwxrwx 0/0               0 2023-01-26 03:03 var/spool/mail -> ../mail
drwxrwxrwt 0/0               0 2023-01-26 03:06 var/tmp/
$ docker import my-container-fs.tar imported-ubuntu-image:latest
sha256:67b6cd298ebba5c27954b42063aa1753189091cd26321b20f7e662e5d5c4221c
$ docker run --rm imported-ubuntu-image:latest uname -a
Linux 9d22baaf4879 5.17.0-1026-oem #27-Ubuntu SMP PREEMPT Wed Jan 4 09:51:00 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

The Rockcraft output, on the other hand, is an OCI tarball, containing both the filesystem, but also the OCI manifests and image configuration, so `docker import` cannot cope with that type of input and will not know how to start a container from that.

##### docker load

There is also `docker load`. That is a bit closer to what you're trying to do, in the sense that it converts an "image artifact" into a Docker Daemon-compliant container image.

```bash
$ docker save ubuntu:latest -o ubuntu.tar
$ tar -tvf ubuntu.tar 
-rw-r--r-- 0/0            2299 2023-01-26 05:58 58db3edaf2be6e80f628796355b1bdeaf8bea1692b402f48b7e7b8d1ff100b02.json
drwxr-xr-x 0/0               0 2023-01-26 05:58 d5e9028c535cebbd5d2243c08c51ba634d385964dc6b63987bb37c5b844c4140/
-rw-r--r-- 0/0               3 2023-01-26 05:58 d5e9028c535cebbd5d2243c08c51ba634d385964dc6b63987bb37c5b844c4140/VERSION
-rw-r--r-- 0/0            1320 2023-01-26 05:58 d5e9028c535cebbd5d2243c08c51ba634d385964dc6b63987bb37c5b844c4140/json
-rw-r--r-- 0/0        80326656 2023-01-26 05:58 d5e9028c535cebbd5d2243c08c51ba634d385964dc6b63987bb37c5b844c4140/layer.tar
-rw-r--r-- 0/0             202 1970-01-01 01:00 manifest.json
-rw-r--r-- 0/0              89 1970-01-01 01:00 repositories
$ docker load -i ubuntu.tar 
Loaded image: ubuntu:latest    # notice that Docker already knows the image name, as it's part of the .tar metadata
```

See the `d5e9028c535cebbd5d2243c08c51ba634d385964dc6b63987bb37c5b844c4140/layer.tar` above? That's the actual rootfs tarball (similar to what we were `import`ing in the previous section.

**However:**
```bash
$ docker load -i big_latest_amd64.rock
open /var/lib/docker/tmp/docker-import-718637234/blobs/json: no such file or directory
```

##### why can't you `load` a ROCK into Docker

A ROCK is an image artifact, 

```bash
$ tar -tvf big_latest_amd64.rock
drwxr-xr-x root/root         0 2023-02-06 12:05 blobs/
drwxr-xr-x root/root         0 2023-02-06 12:05 blobs/sha256/
-rw-r--r-- root/root      2128 2023-02-06 12:05 blobs/sha256/43df423ef9be67f3a948c721f93a7ba49547dcd1c8c7baf71ba0db7906f6bb44
-rw-r--r-- root/root   3243174 2023-02-06 12:05 blobs/sha256/61b388252e601d55d79bc55fedcf095259486447924ca62616b142cd98449efd
-rw-r--r-- root/root  29528717 2023-02-06 12:05 blobs/sha256/677076032cca0a2362d25cf3660072e738d1b96fe860409a33ce901d695d7ee8
-rw-r--r-- root/root      1029 2023-02-06 12:05 blobs/sha256/edfe9b093b83a76fa0212afcb35695b6ebf5c2f20a7d5f689970323b5101d299
-rw-r--r-- root/root       441 2023-02-06 12:05 blobs/sha256/f45921ea4f56ae30d13d2da59e3561999aa005f3f6b8a0888e66ab2a1e8c441f
-rw-r--r-- root/root       248 2023-02-06 12:05 index.json
-rw-r--r-- root/root        31 2023-02-06 12:05 oci-layout
```

but Docker can't load it. This is because Docker does not "yet" (for 6 years now :stuck_out_tongue:) support loading OCI artifacts -> https://github.com/moby/moby/issues/25779

----

I hope this helps. I'm closing the issue as this was a request for clarification, but feel free to re-open if any questions remain.
