### ISSUE TITLE
[bug] Pebble layer is being written with service fields in snake case

### ISSUE THREAD

**Issue by cjdcordeiro** [canonical/rockcraft#235]
https://github.com/canonical/rockcraft/blob/c8d27b6e885a7ab08166920b85194eea8edd599b/rockcraft/pebble.py#L85

See an example of the error here: https://github.com/canonical/nginx-rock/pull/6#issuecomment-1513416783

## Goal

 - replace all yaml keys underscored with "-"
 - add a spread test for it

**Comment by tigarmo** [comment]
I don't think we need to 'manually' replace the keys; this issue is happening because the Pydantic model has underscores (as they are Python attributes) but it should be enough to add a `by_alias=True` to the `dict()` call [here](https://github.com/canonical/rockcraft/blob/main/rockcraft/lifecycle.py#L175)

**Comment by cjdcordeiro** [comment]
yep, it is already being proposed in https://github.com/canonical/rockcraft/pull/233/files#diff-2e78c02a1430e75e37cceef3157f4c33ebc785b8693642ebeda5b5d118ec5935R188
